// PhishDetect
// Copyright (c) 2018-2019 Claudio Guarnieri.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package brand

// Slack brand properties.
func Slack() *Brand {
	name := "slack"
	original := []string{"slack"}
	safelist := []string{"slack.com"}
	suspicious := []string{
		// "slqck", "slabk", "slaak",
		// "slagk", "slakk", "slask",
		// "slacj",
		// "slacc", "xn--slk-bla9a", "xn--sck-9oa82a",
		// "xn--slk-rpa3009a", "xn--lck-bza54j", "xn--slk-fla434b",
		// "xn--slal-2cbb", "xn--slclk-hra", "xn--slk-3la331c",
		// "xn--lck-mla783v", "xn--slclc-hra", "xn--lck-mla2277c",
		// "xn--lak-7pa1257c", "xn--s1ak-nod", "xn--sack-g9bc",
		// "xn--sak-3la76b", "xn--sacc-g9bc", "xn--sick-1na",
		// "xn--slal-n6db", "xn--sck-ila87q", "xn--s1ck-rzb",
		// "xn--slc-tgz636f", "xn--slacl-zj9c", "xn--slc-rla0407c",
		// "xn--s1ck-1mb", "xn--siak-2oa", "xn--lak-7pa11b",
		// "xn--slacl-okb", "xn--slk-bla9q", "xn--slaik-6xa",
		// "xn--lck-tvd2862c", "siaclc", "xn--slk-bla908a",
		// "siaclk", "xn--slc-bla567a", "xn--1ack-f9d",
		// "xn--slk-i4a823b", "xn--slc-onb5245c", "xn--s1ck-roa",
		// "xn--lck-9ka204v", "xn--sak-rpa29o", "xn--sck-gsb3k",
		// "xn--slack-7nc", "xn--slk-rla9o", "xn--lck-ula20d",
		// "xn--sick-moa", "xn--lak-rpa60q", "xn--slc-hsb02p",
		// "xn--lck-mla225b", "xn--slacl-kxa", "xn--ack-evb824t",
		// "xn--slk-nla4p", "xn--slacl-8xa", "xn--siac-jc0c",
		// "xn--sck-hwa976b", "xn--sac-fvb6805c", "xn--iack-uv0c",
		// "xn--slacl-2ra", "xn--slc-nla5407c", "xn--lac-bza251a",
		// "xn--sck-mla37q", "xn--slk-rla43f", "xn--lck-qla70d",
		// "xn--sla-4la927a", "xn--s1ck-1na", "xn--sla-spa965a",
		// "s1ac1k", "xn--lak-3la663v", "s1ac1c",
		// "xn--slc-idb0785c", "xn--slack-q4a", "xn--lck-9ka20s",
		// "xn--laclk-jjy", "xn--lck-9oa263b", "xn--1ack-k5a",
		// "xn--laclc-jjy", "xn--lck-9oa72q", "xn--lacik-g2e",
		// "xn--lck-nnb76b", "xn--lck-ehd54d", "xn--slack-2sa",
		// "xn--lac-ryc5804c", "xn--sck-fvb491a", "xn--slk-rzc85c",
		// "xn--lak-5ed1h", "xn--lck-ila725b", "xn--sick-6na",
		// "xn--s1ck-hse", "xn--slk-3la86i", "slac1k",
		// "xn--lck-bza53h", "slaclk", "xn--lck-qla7177c",
		// "xn--slk-rpa35l", "xn--slk-hsb46p", "xn--sla-ryc8b",
		// "xn--s1ak-2oa", "xn--siak-nod", "xn--lak-5ed1143c",
		// "xn--slk-bla45f", "xn--ack-evb36v", "xn--slk-vlak",
		// "xn--slk-rzc3055a", "xn--lac-ryc58e", "xn--slk-rla9q",
		// "xn--slcik-yqa", "xn--lck-6cd7p", "xn--slalc-mkb",
		// "xn--slc-idb57v", "xn--lck-ela79r", "xn--sla-ryc88d",
		// "xn--slk-bpau", "xn--lak-rpa602v", "xn--sck-qla38b",
		// "xn--lck-9ka72d", "xn--slk-i4a315a", "xn--slack-k9x",
		// "xn--lak-7pa123b", "xn--slclc-lwb", "xn--slc-bpa5886c",
		// "xn--lck-bza09c", "xn--sack-g9t", "xn--slacl-kde",
		// "xn--1ack-zhu", "xn--lacik-jjy", "xn--slk-vla414b",
		// "xn--sacc-01ac", "xn--slaci-zj9c", "xn--sack-01ac",
		// "xn--laclk-tcb", "xn--slclc-ucc", "siacik",
		// "xn--laclc-tcb", "xn--slcik-swa", "xn--slclk-ucc",
		// "xn--slk-3la3l", "siacic", "xn--iack-pdc",
		// "xn--slclc-yqa", "xn--lak-i4a6986c", "xn--slc-jla0507c",
		// "xn--saclk-k7a", "xn--sck-nnb35a", "xn--slk-fla4a",
		// "xn--saclc-k7a", "xn--slcik-1jc", "xn--sck-ela38q",
		// "xn--slc-ryc71l", "xn--ack-bza47k", "xn--slk-rpa379b",
		// "xn--slack-n41s", "xn--slk-idb91w", "s1aclk",
		// "xn--slcik-4qa", "xn--lck-9oa25b", "xn--lck-0xb0117a",
		// "xn--slk-nlau", "s1aclc", "xn--slk-bla934b",
		// "xn--lak-0xb12n", "xn--lak-bza628a", "xn--lac-0xb2794c",
		// "xn--slalc-3ye", "xn--ack-gwa8j", "slacilk",
		// "slacilc", "xn--sick-6q5a", "xn--lck-qla283v",
		// "xn--slcik-nra", "xn--slal-ntab", "xn--sack-vpa",
		// "xn--s1ck-6na", "xn--slc-vla047a", "xn--ack-evb3675c",
		// "xn--sck-fvb97t", "xn--sick-1sa", "xn--slk-rpa36n",
		// "xn--slaik-ixa", "xn--slalc-0ra", "xn--slack-tbe",
		// "xn--slk-jla9p", "xn--slk-vla4q", "xn--sick-1mb",
		// "xn--slclk-k11b", "xn--slk-nla93f", "xn--slc-fla5507c",
		// "xn--s1ck-63d", "xn--sac-hwa672a", "xn--s1ck-coa",
		// "xn--sck-hwa96k", "xn--slk-rpa851b", "xn--slclk-swa",
		// "xn--slk-idb942a", "xn--lck-ila71d", "xn--slclc-swa",
		// "xn--slc-uvd5002c", "xn--sla-j4a9126c", "xn--lck-gsb2985c",
		// "xn--slk-i4a81h", "xn--lck-9oa2657c", "xn--sck-ula87b",
		// "xn--lac-ryc057r", "xn--lck-qla28r", "xn--lck-qla715b",
		// "xn--slack-n7a", "xn--slacc-n7a", "xn--lck-ila7277c",
		// "xn--sla-8pa4486c", "xn--slclc-nra", "xn--slclc-sqa",
		// "xn--lck-9oa722v", "xn--slclk-nra", "xn--lck-bza5858a",
		// "xn--slclk-sqa", "xn--sack-5pa", "xn--siak-nta",
		// "xn--slk-onb40y", "xn--slc-7cd0282c", "xn--slack-13a",
		// "xn--sak-7pa27o", "xn--s1ac-jc0c", "xn--lak-bza1u",
		// "xn--slalc-ixa", "slaclik", "xn--lck-hdb743a",
		// "xn--lck-0xb080a", "xn--slk-3la31n", "xn--sak-hwa023a",
		// "xn--slk-nla4r", "xn--slclc-5ve", "xn--slaik-3ye",
		// "xn--slk-onb47r", "xn--lck-nnb2016c", "xn--slcik-hra",
		// "xn--lck-sgzq69f", "xn--lck-ula77r", "xn--slk-fla4s",
		// "xn--sck-9ka30c", "xn--lck-nnb20z", "xn--sac-hwa1756c",
		// "xn--lck-ela793v", "xn--sack-5md", "xn--slk-bpa462b",
		// "xn--sack-0ya", "xn--lck-ula2177c", "xn--slk-vla4o",
		// "xn--slaik-0ra", "xn--sck-hdb89e", "xn--slk-i4a36a",
		// "xn--slk-rzc37k", "xn--slk-hsb49v", "xn--slalk-ide",
		// "xn--lck-mla21d", "xn--slc-fla067a", "xn--slalc-ide",
		// "xn--slcik-k11b", "xn--slacc-koc", "xn--lak-rpa13b",
		// "slac1c", "xn--slack-koc", "xn--slalk-6xa",
		// "xn--sack-lza", "xn--slalc-6xa", "s1acik",
		// "xn--sick-63d", "xn--sla-j4a42z", "xn--ack-gwa319u",
		// "xn--sck-hwa468a", "xn--sck-qla86q", "xn--lac-ggqv57p",
		// "xn--sak-i4a74i", "xn--lak-i4a165u", "xn--slalk-3ye",
		// "xn--lacik-569c", "xn--lak-rpa143b", "xn--slcik-5ve",
		// "xn--s1ac-end", "xn--sack-bnb", "xn--lck-nnb767t",
		// "xn--slaik-mkb", "xn--lck-9ka735b", "xn--slcik-bra",
		// "xn--sla-8pa945a", "xn--lck-6cd7943c", "xn--lck-ehd5774a",
		// "xn--slk-bpa4b", "xn--lak-7pa681v", "xn--slc-ryc20d",
		// "xn--sick-rzb", "xn--slk-rla914b", "xn--sck-ula36q",
		// "xn--slack-fta", "xn--lck-ula215b", "xn--lck-hdb7456c",
		// "xn--laclc-g2e", "xn--lak-3la105b", "xn--laclc-esc",
		// "xn--laclk-g2e", "xn--slk-rlap", "xn--lak-i4a696a",
		// "xn--laclk-esc", "xn--sick-coa", "xn--slclc-1jc",
		// "xn--sak-fvb56u", "xn--slclk-1jc", "xn--s1ck-6q5a",
		// "xn--saclk-hoc", "xn--slaci-0be", "xn--lak-rzc607r",
		// "xn--saclc-hoc", "xn--slal-7tab", "xn--slk-nla424b",
		// "xn--iack-zhu", "xn--lck-hdb21g", "xn--slclk-lwb",
		// "xn--lak-0xb15t", "xn--slack-zwb", "xn--slk-7pa3898a",
		// "xn--siak-2cb", "xn--sick-hoa", "xn--lak-3la19c",
		// "xn--slc-jla557a", "xn--lck-bza047a", "xn--slal-2oab",
		// "xn--1ack-pdc", "xn--s1ck-r5b", "slacllk",
		// "xn--slk-7pa831b", "slacllc", "xn--slcik-sqa",
		// "xn--sck-ela89b", "xn--sck-9oa31p", "xn--lac-0xb77m",
		// "xn--slk-3la32p", "xn--sick-r5b", "xn--slk-jla44f",
		// "xn--lck-gsb755t", "xn--slclk-bra", "xn--lck-tvd743q",
		// "xn--slclc-bra", "xn--slacl-5ye", "xn--slacl-0be",
		// "xn--slk-vla487a", "xn--s1ak-nta", "xn--1ack-uv0c",
		// "xn--slk-bla9s", "xn--slclc-k11b", "xn--lacik-esc",
		// "xn--siak-n6d", "xn--slk-jla9r", "xn--slalk-0ra",
		// "xn--slk-5ed3784a", "xn--slk-jla997a", "xn--sak-rpa70a",
		// "xn--lck-mla78r", "xn--slk-fla408a", "xn--slc-vla5307c",
		// "xn--slaik-ide", "xn--lak-rzc14e", "xn--sla-4la4207c",
		// "xn--slk-i4a80f", "xn--sack-0h7o", "xn--slk-3la813b",
		// "xn--lck-gsb7v", "xn--sak-hwa56a", "xn--sac-fvb19n",
		// "xn--siac-end", "xn--lac-bza7446c", "xn--lck-ela2377c",
		// "xn--slc-nla057a", "slaciik", "xn--lac-230b21a",
		// "xn--slk-7cd9f", "xn--lck-ela22d", "xn--lck-ula773v",
		// "xn--slcik-3of", "xn--ack-evb8i", "xn--slk-7pa359b",
		// "xn--sak-3la25q", "xn--slalk-ixa", "xn--slk-rpa80h",
		// "xn--lck-0xb56s", "xn--slk-i4a8538a", "xn--sck-hwa41e",
		// "xn--lck-hdb212u", "xn--iack-k5a", "xn--sla-szc4633c",
		// "xn--lac-ehd7362c", "xn--s1ck-1sa", "xn--lck-ila293v",
		// "xn--sla-spa4686c", "xn--sck-hwa95i", "xn--lacik-tcb",
		// "xn--slcik-ucc", "xn--s1ck-hoa", "xn--sacik-k7a",
		// "xn--lak-3la66r", "slacic", "xn--slk-7pa33l",
		// "slacik", "xn--lck-ggq042f", "xn--lak-i4a16j",
		// "xn--slk-fla4q", "xn--slc-bpa095a", "xn--sacik-hoc",
		// "xn--lak-3la1077c", "xn--slcik-lwb", "xn--slk-rla987a",
		// "xn--sak-fvb53o", "xn--lck-ela235b", "xn--slk-nla497a",
		// "xn--sak-7pa7y", "xn--ack-gwa31n", "xn--slclk-3of",
		// "xn--s1ck-moa", "xn--slk-7pa34n", "xn--slclc-3of",
		// "xn--sick-hse", "xn--slk-3la3619a", "xn--slclk-yqa",
		// "xn--sck-9ka88q", "xn--slk-bpa436a", "xn--slk-jlaz",
		// "xn--ack-gwa8427c", "xn--s1ak-2cb", "xn--lak-rpa1457c",
		// "xn--slclk-4qa", "xn--s1ak-n6d", "xn--laclk-569c",
		// "xn--slk-fla94f", "xn--laclc-569c", "xn--slclk-5ve",
		// "xn--slk-7pa88g", "xn--slc-rla547a", "xn--lck-ila29r",
		// "s1ack", "xn--sick-roa", "xn--slk-vla92f",
		// "xn--sla-6ed4372c", "xn--s1ak-7ta", "xn--iack-f9d",
		// "xn--sck-mla88b", "xn--slc-ryc7455a", "xn--lak-bza691a",
		// "xn--lck-bza555b", "xn--lak-rzc1404c", "xn--slc-bla0607c",
		// "xn--slk-jla924b", "xn--ack-gwa840b", "xn--lak-5ed670r",
		// "xn--slc-onb03r", "xn--siak-7ta", "xn--slal-nodb",
		// "xn--sck-fvb4227a", "xn--sck-hwa9078a", "xn--lck-9ka7377c",
		// "xn--lck-gsb29w", "xn--sck-ila39b", "xn--slk-5ed34e",
		// "xn--slc-hsb5125c", "xn--lck-6cd261r", "xn--slclc-4qa",
		// "xn--sak-hwa059a", "xn--lak-7pa68p", "xn--slalk-mkb",
		// "xn--sack-58b", "xn--slk-bpa97d", "s-lack",
		// "sl-ack", "sla-ck", "slac-k",
		// "slaxck", "sla1ck", "slazck",
		// "sladck", "sklack", "slafck",
		// "slsack", "slqack", "slayck",
		// "slwack", "sla2ck", "sl2ack",
		// "solack", "smlack", "splack",
		// "slasck", "sl1ack", "slkack",
		// "slpack", "slacvk", "slacdk",
		// "slawck", "slyack", "slacfk",
		// "slaqck", "slacxk", "slzack",
		// "slavck", "sloack", "slmack",
		// "slck", "slak",
		// "slac", "slaack",
		// "sllack", "slacck", "sslack",
		// "sl2ck", "sl1ck", "spack", "zlack",
		// "dlack", "sladk", "slafk",
		// "slavk", "slwck", "xlack",
		// "slzck", "slsck", "slyck",
		// "slacl", "slacm", "slaxk",
		// "alack", "skack", "elack",
		// "lsack", "salck", "slcak",
		// "slakc", "slock", "slackcom",
	}

	return &Brand{
		Name:       name,
		Original:   original,
		Safelist:   safelist,
		Suspicious: suspicious,
	}
}
