package brand

// Microsoft brand properties.
func Microsoft() *Brand {
	name := "microsoft"
	original := []string{"microsoft", "microsoftonline", "onedrive"}
	whitelist := []string{
		"microsoft.com", "microsoftonline.com", "office.com", "live.com",
		"onedrive.com", "s-microsoft.com", "sharepoint.com",
	}
	suspicious := []string{
		"microsofta", "microsoftb", "microsoftc", "microsoftd", "microsofte",
		"microsoftf", "microsoftg", "microsofth", "microsofti", "microsoftj",
		"microsoftk", "microsoftl", "microsoftm", "microsoftn", "microsofto",
		"microsoftp", "microsoftq", "microsoftr", "microsofts", "microsoftt",
		"microsoft", "microsoftv", "microsoftw", "microsoftx", "microsofty",
		"microsoftz", "licrosoft", "oicrosoft", "iicrosoft", "eicrosoft",
		"mhcrosoft", "mkcrosoft", "mmcrosoft", "macrosoft", "mycrosoft",
		"mibrosoft", "miarosoft", "migrosoft", "mikrosoft", "misrosoft",
		"micsosoft", "micposoft", "micvosoft", "miczosoft", "micbosoft",
		"mic2osoft", "micrnsoft", "micrmsoft", "micrksoft", "micrgsoft",
		"microroft", "microqoft", "microwoft", "microcoft", "micro3oft",
		"microsnft", "microsmft", "microskft", "microsgft", "microsogt",
		"microsodt", "microsobt", "microsont", "microsovt", "microsof",
		"microsofv", "microsofp", "microsofd", "microsof4", "xn--micrsoft-q4a",
		"xn--icrosoft-2wd", "xn--micrsoft-6ji", "micr0s0ft", "xn--micrsft-3nib",
		"xn--mirosoft-gch", "xn--mirosoft-1eg", "xn--mirosoft-29a",
		"xn--microsof-hfg", "xn--microsft-4dg", "xn--micosoft-8zd",
		"xn--micrsft-cpfb", "xn--microoft-ohh", "xn--micrsft-djgb",
		"xn--micrsft-o0ab", "xn--micrsoft-pec", "xn--micrsoft-qbh", "nicrosoft",
		"xn--microsft-rec", "xn--icrosoft-qy7c", "xn--micrsft-djgb",
		"xn--microsft-sbh", "xn--mirosoft-t0a", "nnicrosoft", "m1crosoft",
		"rnicrosoft", "xn--micosoft-847c", "xn--micrsft-g5bb",
		"xn--micrsft-zmhb", "xn--microsft-m90d", "xn--microsft-sbh",
		"xn--mcrosoft-c2a", "xn--micosoft-00d", "rricrosoft",
		"xn--micrsft-fx4cb", "xn--icrosoft-39g", "xn--microsot-x9b",
		"xn--micrsft-w2cb", "xn--microoft-857f", "xn--micrsoft-7fd",
		"xn--micosoft-v7g", "xn--microsft-8ji", "xn--microoft-qvb",
		"xn--mirosoft-18a", "xn--mirosoft-76b", "xn--microsof-vch",
		"xn--microsot-oxh", "xn--micrsft-cpfb", "xn--microsot-vlg",
		"xn--mcrosoft-k99a", "xn--micrsoft-180d", "xn--mcrosoft-gcg",
		"xn--microoft-bo0b", "xn--micrsoft-2dg", "xn--micrsoft-qbh",
		"xn--microsft-4dg", "xn--mcrosoft-6152a", "micros0ft",
		"xn--microoft-l1d", "xn--micosoft-zzd", "xn--micrsoft-y3a", "micr0soft",
		"xn--microsft-380d", "xn--micrsoft-k90d", "xn--mcrosoft-tkb",
		"xn--micrsft-d1ab", "mlcrosoft", "xn--microsft-03a", "xn--microsof-vxb",
		"xn--micrsoft-2dg", "xn--micrsft-vx4cb", "xn--microsft-9fd",
		"xn--mcrosoft-sjb", "xn--micrsoft-tpj", "xn--icrosoft-g89c",
		"xn--mcrosoft-pqc", "xn--microsft-vpj", "xn--microsft-s4a",
		"xn--mcrosoft-u2a", "xn--mcrosoft-1ud", "m-icrosoft", "mi-crosoft",
		"mic-rosoft", "micr-osoft", "micro-soft", "micros-oft", "microso-ft",
		"microsof-t", "micr0osoft", "microsolft", "micros9oft", "micrkosoft",
		"mikcrosoft", "microsofct", "micrfosoft", "mkicrosoft", "mic4rosoft",
		"microsotft", "microskoft", "microsaoft", "microswoft", "microsopft",
		"microasoft", "mifcrosoft", "micro0soft", "micr9osoft", "mi8crosoft",
		"microsqoft", "microsxoft", "microsoift", "microsdoft", "microlsoft",
		"micrlosoft", "microsorft", "microsokft", "microsofvt", "microesoft",
		"mijcrosoft", "micfrosoft", "microsioft", "microseoft", "microsodft",
		"micros0oft", "microysoft", "micrtosoft", "miucrosoft", "midcrosoft",
		"micrposoft", "micvrosoft", "miocrosoft", "microsocft", "microsovft",
		"micriosoft", "m9icrosoft", "microqsoft", "mictrosoft", "mic5rosoft",
		"microsogft", "microso0ft", "microsofdt", "micropsoft", "micr4osoft",
		"microzsoft", "microwsoft", "mixcrosoft", "microso9ft", "microsyoft",
		"microksoft", "microszoft", "micro9soft", "mivcrosoft", "microsofgt",
		"mi9crosoft", "microdsoft", "micreosoft", "micrdosoft", "microspoft",
		"microxsoft", "muicrosoft", "micxrosoft", "microsofrt", "microisoft",
		"m8icrosoft", "moicrosoft", "microsloft", "micr5osoft", "micdrosoft",
		"micerosoft", "mjicrosoft", "microoft", "microsof", "mcrosoft",
		"icrosoft", "mirosoft", "micrsoft", "microsot", "micosoft", "microsft",
		"microosoft", "microsooft", "microsofft", "miccrosoft", "microssoft",
		"miicrosoft", "micrrosoft", "mmicrosoft", "microsort", "microsofg",
		"microspft", "micrisoft", "mivrosoft", "microzoft", "mucrosoft",
		"micrpsoft", "micrlsoft", "mictosoft", "mifrosoft", "microsofr",
		"microsof5", "microxoft", "mjcrosoft", "microsoct", "picrosoft",
		"m8crosoft", "microsof6", "microeoft", "miceosoft", "microsott",
		"m9crosoft", "micdosoft", "mixrosoft", "microsift", "mic5osoft",
		"microyoft", "mic4osoft", "microsofz", "kicrosoft", "microdoft",
		"micfosoft", "midrosoft", "microsoff", "microsofy", "microslft",
		"micros9ft", "jicrosoft", "microaoft", "mocrosoft", "micr9soft",
		"m.icrosoft", "mi.crosoft", "mic.rosoft", "micr.osoft", "micro.soft",
		"micros.oft", "microso.ft", "microsof.t", "imcrosoft", "mcirosoft",
		"mircosoft", "micorsoft", "micrsooft", "microosft", "microsfot",
		"microsotf", "microsaft", "micrusoft", "microseft", "mecrosoft",
		"microsuft", "micresoft", "micrasoft", "microsoftcom",
	}

	suspicious = append(suspicious, []string{
		"onedrivea", "onedriveb", "onedrivec", "onedrived", "onedrivee",
		"onedrivef", "onedriveg", "onedriveh", "onedrivei", "onedrivej",
		"onedrivek", "onedrivel", "onedrivem", "onedriven", "onedriveo",
		"onedrivep", "onedriveq", "onedriver", "onedrives", "onedrivet",
		"onedrive", "onedrivev", "onedrivew", "onedrivex", "onedrivey",
		"onedrivez", "nnedrive", "mnedrive", "knedrive", "gnedrive", "ooedrive",
		"oledrive", "ojedrive", "ofedrive", "onddrive", "ongdrive", "onadrive",
		"onmdrive", "onudrive", "oneerive", "onefrive", "onelrive", "onetrive",
		"onedsive", "onedpive", "onedvive", "onedzive", "onedbive", "oned2ive",
		"onedrhve", "onedrkve", "onedrmve", "onedrave", "onedryve", "onedriwe",
		"onedrite", "onedrire", "onedrife", "onedri6e", "onedrivd", "onedrivg",
		"onedriva", "onedrivm", "onedriv", "xn--onedrve-7gc", "xn--ondriv-cvfe",
		"xn--ondrive-cdh", "xn--ondriv-qh8be", "xn--ondriv-4ofe",
		"xn--onerive-0cd", "xn--onerive-wsh", "xn--nedrive-s2c",
		"xn--onedrve-znf", "xn--ondrive-ss4c", "xn--ondrive-kya",
		"xn--onedriv-pya", "xn--onedriv-hdh", "xn--onedriv-ehg",
		"xn--onerive-i7a", "xn--nedrive-7of", "xn--onedrive-u0e", "omedrive",
		"xn--nedrive-k0a", "xn--onedriv-g9a", "xn--nedrive-bx4c",
		"xn--nedrive-vmh", "onedrlve", "xn--ondrive-cog", "oredrive",
		"xn--ondrive-e8a", "onebrive", "xn--nedrive-80a", "xn--nedrive-rx4c",
		"xn--ondriv-c5ae", "xn--ondriv-x4ae", "xn--ondrive-b9a",
		"xn--onedriv-w9a", "xn--onedrie-zvg", "xn--ondrive-sya",
		"xn--onedrve-yeb", "xn--onedrve-sza", "xn--onedriv-4mf",
		"xn--nedrive-7of", "xn--onedive-fmd", "xn--ondrive-x7a",
		"xn--onedriv-hya", "xn--onedrve-n95a", "xn--onedriv-xya",
		"xn--ondrive-u8a", "xn--ondriv-chge", "xn--ondrive-r9a",
		"xn--ondriv-jyee", "xn--ondriv-q3ae", "onedirive", "xn--nedrive-zni",
		"xn--onedrve-6gd", "xn--oedrive-3jb", "xn--onedive-ild",
		"xn--onedriv-j8a", "xn--ondriv-j4ae", "xn--ondriv-qvae",
		"xn--onerive-whi", "xn--nedrive-8ig", "xn--onedive-q51c",
		"xn--onedrve-vfb", "oneclrive", "0nedrive", "xn--ondriv-43ae",
		"xn--ondrive-cya", "xn--onedriv-xs4c", "xn--onedrve-rf1z", "onedr1ve",
		"xn--onedriv-27a", "xn--ondrive-zmf", "xn--ondriv-jvae",
		"xn--ondriv-cvae", "xn--onedrie-xof", "xn--onedive-qld",
		"xn--nedrive-8ig", "xn--onedriv-z8a", "xn--nedrive-c5b", "onedlrive",
		"xn--onedrve-cza", "xn--ondrive-8gg", "xn--onedriv-hog",
		"xn--onedive-ugg", "o-nedrive", "on-edrive", "one-drive", "oned-rive",
		"onedr-ive", "onedri-ve", "onedriv-e", "onewdrive", "onedri9ve",
		"onezdrive", "onesdrive", "on4edrive", "onsedrive", "onedriove",
		"onedr4ive", "onedfrive", "onedrdive", "onedruive", "onedrjive",
		"onbedrive", "onedrigve", "onedreive", "oneddrive", "onedr9ive",
		"ojnedrive", "onedtrive", "onedrkive", "oneedrive", "onedri8ve",
		"onedribve", "onedrikve", "onederive", "onedrijve", "ondedrive",
		"onedxrive", "ohnedrive", "onzedrive", "onedrivge", "one3drive",
		"onedsrive", "onedrrive", "on3edrive", "onerdrive", "obnedrive",
		"onedr5ive", "one4drive", "onecdrive", "oned5rive", "onedrifve",
		"onredrive", "onmedrive", "onhedrive", "onedrivbe", "onedriuve",
		"onedr8ive", "onedroive", "omnedrive", "onjedrive", "onedrtive",
		"oned4rive", "onedrivce", "onedcrive", "onefdrive", "onedrivfe",
		"onedrfive", "onwedrive", "onexdrive", "onedricve", "onedrve",
		"onedive", "onerive", "onedriv", "nedrive", "oedrive", "ondrive",
		"onedrie", "oonedrive", "onedrivve", "onnedrive", "onedriive",
		"onedeive", "onedtive", "oneddive", "onecrive", "obedrive", "lnedrive",
		"onedfive", "onedr8ve", "onedriv3", "onesrive", "onedr9ve", "pnedrive",
		"on3drive", "ohedrive", "onedriv4", "onedribe", "inedrive", "onedrove",
		"onzdrive", "onwdrive", "on4drive", "9nedrive", "oned5ive", "onedrivz",
		"onedrivw", "oned4ive", "onexrive", "onrdrive", "onedrivs", "onedrivr",
		"onsdrive", "onedrige", "onedrjve", "onedruve", "onedrice", "onerrive",
		"o.nedrive", "on.edrive", "one.drive", "oned.rive", "onedr.ive",
		"onedri.ve", "onedriv.e", "noedrive", "oendrive", "onderive",
		"onerdive", "onedirve", "onedrvie", "onedriev", "onidrive",
		"onedreve", "onedrivo", "unedrive", "anedrive", "onedrivi",
		"enedrive", "onodrive", "onedrivecom",
	}...)

	return &Brand{
		Name:       name,
		Original:   original,
		Whitelist:  whitelist,
		Suspicious: suspicious,
	}
}
